version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/examples/default"
    schedule:
      interval: "weekly"

  # Workflow files stored in the
  # default location of `.github/workflows`
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
